### ISSUE TITLE
Problem about cameras

### ISSUE THREAD

**Issue by dongyh20** [StanfordVL/OmniGibson#235]
Thanks for your impressive work! We hope to follow your work and develop in this environment. We want to edit the camera position and orientation of a specific robot without constraints, like the robot `fetch` for instance, but we failed to find the proper functions that enable this.  @cremebrule @ChengshuLi 

Currently we manually control the camera with the provided control idx, but it has two problems: the first one is the camera of the robot can only move left or right, but cannot be placed higher. 

The second one is when turning the robot around, the camera will be rotated by an angle, but we have no idea why this happens 
![1](https://github.com/StanfordVL/OmniGibson/assets/122193775/2778a319-0fd8-4175-852e-19868d2455ce)

**Comment by cgokmen** [comment]
If you want to edit the camera pose without it being chained to the robot, you can disable the robot's camera and instead add a separate VisionSensor into the scene. You can just move the VisionSensor (sensor_obj.set_position_orientation) arbitrarily. You might need to do some work to wire your custom VisionSensor into the environment's observation if you are using that interface.

An alternative might be simply reparenting the robot's VisualSensor in the prim tree (e.g. change its parent to be the World prim rather than the robot head link):
```
robot_sensor = robot.sensors[...]  # find the key for the vision sensor, I'm not sure what it is
robot_sensor.change_prim_path("/World/camera")  # reparent it
robot_sensor.set_position_orientation()  # move it where you want
# robot observation should still be coming from the sensor
```

The camera should not be rolling like that unless you are also inputting a roll action for the camera when you move.
