### ISSUE TITLE
request for checkpoint

### ISSUE THREAD

**Issue by Draculair** [StanfordVL/OmniGibson#271]
Hi, Do you have the pre-trained checkpoint of the baseline from the experiments in your paper in the repository? Thanks.

**Comment by cgokmen** [comment]
Unlikely (since a lot of code has been changed since then), but @j96w for visibility

**Comment by Draculair** [comment]
@j96w Can I trouble you for the checkpoints in your paper? Thanks

**Comment by j96w** [comment]
Hey @Draculair, sorry for the late response. Due to the large changes over the code base, the trained checkpoints (trained in Sep. 2021) are no longer compatible with the current infra (released in Seq 2023).

**Comment by Draculair** [comment]
What about the latest version, is it availale? Or can you tell me how to train the basic skills in the benchmark? Thank you!

**Comment by j96w** [comment]
Hey @Draculair, we didn't train skills in our previous submission, the model is trained with RL to generate high-level skill selection instead of actual robot motor commands. You can check out our study paper for more information about that. About the latest version, we do have several on-going projects but most of them are not following the high-level skill training fashion anymore due to the rapid development of new decision-making methods. We will let you know when we are ready to release more.

**Comment by Draculair** [comment]
Hey @j96w, I'd like to ask how you drive the robot to perform these decomposed actions (skills) when you have done the task decomposition (decision making)? Thanks

**Comment by cgokmen** [comment]
You can take a look at our ongoing effort to produce action primitives. This is in development currently but it'll give you an idea of how you can implement these things (e.g. driving the robot around). https://github.com/StanfordVL/OmniGibson/blob/action-primitives/omnigibson/action_primitives/starter_semantic_action_primitives.py
