### ISSUE TITLE
Fix instance segmentation by switching to Replicator APIs

### ISSUE THREAD

**Issue by cgokmen** [StanfordVL/OmniGibson#458]

**Comment by hang-yin** [comment]
Replicator semantic segmentation returns a dictionary called `idToLabels` that looks like: `{'0': {'class': 'BACKGROUND'}, '2': {'class': 'agent'}}`.
We also have a pre-existing mapping between class names and IDs (e.g. `{'background: 555, agent: 1'}`).
Since they don't match, preventing us from having access to global semantics information, we will need to remap the IDs on the semantic segmentation observations to our labels.
