### ISSUE TITLE
Predefined Simple Tasks for Initial Testing of Codebase

### ISSUE THREAD

**Issue by ShahRutav** [StanfordVL/OmniGibson#684]
Hi, thanks for the great open-source platform!

I want to test simply moving to an object and picking up the object using Tiago. Do you have simple predefined tasks that don't have many object loadings to iterate faster during development? I am looking at the [Grasping Demo Example](https://behavior.stanford.edu/omnigibson/getting_started/examples.html#robot-grasping-demo). However, it uses DummyTask with no task observations and success condition.

If not, do you have any tutorials or examples that I can use to create my own tasks?

**Comment by cgokmen** [comment]
Is it explicitly a BEHAVIOR-1K task that you want to solve, or do you want to just find a pick-and-place task?

1. To use an existing task but perhaps speed things up a bit, you can use the [knowledgebase](https://behavior.stanford.edu/knowledgebase) to browse tasks and find a suitable one that is simple enough. Then, to make it load faster, you can use the load_room_types argument of the scene in the config file to make OmniGibson load only a particular room type for faster loads, or to narrow it even further, you can use load_object_categories to load just certain object categories! Be sure to load walls+floors+ceilings and also any object categories that are involved in your selected task.
2. To make a custom predicate logic task like the BEHAVIOR ones, `pip uninstall bddl`, then `git clone https://github.com/StanfordVL/bddl.git`, go into that repo and `pip install -e .` to install an editable version. You can then go into the activity_definitions directory to create your own task's folder and then in that folder create the BDDL task definition (the format is pretty simple, look at some examples) or the documentation on the BDDL repo [here](https://github.com/StanfordVL/bddl/tree/master/docs?tab=readme-ov-file#example-bddl-activity). You can then load that task into omnigibson using the online_sampling=True argument (this means instead of trying to find a pre-configured scene for this task, one will be configured for you at load time) - see the behavior_task_example for how to do this.
3. You can write your own custom task class to provide your own custom success / reward / termination condition. You can see the requirements of this by looking at the existing tasks and the base task definition.

I'd recommend option 1 for a really quick start, plus your work would be transferrable to an actual BEHAVIOR task success! Let us know how it goes. Feel free to reopen for further help or ping us on Discord.
