### ISSUE TITLE
Teleoperation

### ISSUE THREAD

**Issue by SshiJwu** [StanfordVL/OmniGibson#694]
Thanks for your greatful work! I want to know whether it currently support to teleoperate robotic arms and dexterous hands, such as franka+allegro hand.

**Comment by cgokmen** [comment]
@wensi-ai

**Comment by wensi-ai** [comment]
Thanks for your interest in OmniGibson. We do have franka + allegro hand implemented [here](https://github.com/StanfordVL/OmniGibson/blob/main/omnigibson/robots/franka_allegro.py), you can check out the `robot_control_example` to see how to teleoperate using keyboard. Unfortunately we don't have other teleoperation method implemented due to the dexterity of hand.
