### ISSUE TITLE
issue install from the source code

### ISSUE THREAD

**Issue by JiaheXu** [StanfordVL/OmniGibson#77]
Hi developers,
    When I follow the tutorial to build the env from source following [https://behavior.stanford.edu/omnigibson/getting_started/installation.html#explore-omnigibson](url), I found I cannot find carb
`
Traceback (most recent call last):
  File "/home/jiahexu/anaconda3/envs/omnigibson/lib/python3.7/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/home/jiahexu/anaconda3/envs/omnigibson/lib/python3.7/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/jiahexu/OmniGibson/omnigibson/__init__.py", line 77, in <module>
    from omnigibson.app_omni import OmniApp
  File "/home/jiahexu/OmniGibson/omnigibson/app_omni.py", line 17, in <module>
    import carb
ModuleNotFoundError: No module named 'carb'

pip3 install carb
ERROR: Could not find a version that satisfies the requirement carb (from versions: none)
ERROR: No matching distribution found for carb
`
I am using ubuntu20.04, do I need to change another version of OS?

**Comment by cgokmen** [comment]
Hi,

Carb is one of the modules that come with the Isaac Sim setup. Normally this error happens when your environment (especially the PATH variables) is not set up correctly. You can try checking out if there were any issues when you ran the setup_conda_env script. If you don't find any issues, my colleague @cremebrule can help you when he's back after New Year's. I also strongly recommend the Docker setup since it's a very quick way of getting started.

Thanks,
Cem
