### ISSUE TITLE
Installation of Isaac Sim 2023.1.1 through Omniverse Launcher Exchange Apps

### ISSUE THREAD

**Issue by ge79puv** [StanfordVL/OmniGibson#898]
Hey there,

I am trying to install Isaac Sim 2023.1.1 through Omniverse Launcher Exchange Apps. However, there is no this version on Omniverse Launcher any more. Could you tell me how to install this version of Isaac Sim?
![屏幕截图 2024-09-22 155208](https://github.com/user-attachments/assets/5038c3c9-1d09-4125-b381-b8df2efe83f7)

Thanks a lot in advance!

BR

**Comment by hang-yin** [comment]
Hi @ge79puv , thanks for reaching out! We will cut a new release for the recent isaac sim versions by the end of this week. Meanwhile, you can take a look at https://behavior.stanford.edu/omnigibson-develop/getting_started/installation.html for the installation guide with our development branch. When you clone our repo, please check out our `og-develop` branch instead of the main branch so that isaac 4.0 and 4.1 are supported.

**Comment by mengxyokok** [comment]
isaac 4.2  is surpported by isaac_4_2 branch  ??
