### ISSUE TITLE
how can I install OmniGibson if I installed issac-sim through pip?

### ISSUE THREAD

**Issue by DawnyWu** [StanfordVL/OmniGibson#899]
I install issac-sim 4.0 by using pip like this https://docs.omniverse.nvidia.com/isaacsim/latest/installation/install_python.html 

so I don't have a folder like `~/.local/share/ov/pkg/Isaac-sim` and no `isaac*.sh` file, how can i install omnigibson? 

and when will the new version of omnigibson release because we cannot install isaac-sim 2023.1.1 anymore. 

Thank you.

**Comment by hang-yin** [comment]
Hi @DawnyWu , thanks for reaching out! We will cut a new release for the recent isaac sim versions by the end of this week. Meanwhile, you can take a look at https://behavior.stanford.edu/omnigibson-develop/getting_started/installation.html for the installation guide with our development branch. When you clone our repo, please check out our `og-develop` branch instead of the main branch so that isaac 4.0 is supported.

**Comment by DawnyWu** [comment]
Thank you so much
